language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.1
  - android-22
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
branches:
  only:
    - master
install:
- true
script:
- "./gradlew build"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: fwqyaWMlGYc61flFH9tgf9Ebb8M/2RD5Ks4w8xDlwHChORugkHwOB2xEsuuM/nRYSosV4GXgwNmz7IzAKLtarasGYrS2LY96r8y86PWbUPulGYnhB2XnUEO09Bc/ehOc5YbxNqIdb12+zIZGcN/GN6A+0We1Yp9Ui3GRTyKMU2nDBai0myIrGq3VfaKu94fkGCuSvwTSvOGydtfYDI/EpxqT/hQxaKJHTPX0rrQaflPisbuHK07T5cJKg9QqiGOJwMBCVtP/kGzdSxjwsYD0GJaugVQmUvg9VIyNejqdlTgqxuwnIrLjX5WNXUljlJrZ3GXlt8+628Jh4GlorRuMvHvHsdacxvZrXeZnvreD8ZPrnr35J5HUXxc8ea0CfCNI0uvW15ph2IMYL00QkI/ZP5y93Dwx89v24pCu7aBRxwEnO3vsg84EweX4Em9LNXGkW0NwvqlP+qPJtWF2Wn0b+8+Fk6LwV0BUkCGYvmpP6Qk9JEDwUotZM/D3t9AEeLyvUprAf1hO+/O86qlxNtmGV4uJlMOZgpcmwGPcQjim4IP/bqe+YF20suetvaUMO0guA+pjebB2F9aKlQ1C27dze7VGEhrzxVmjIvs6gnXksL5DOCQwiYd6pTQNlQQLgbhrs/40dPdm0oazAS5KJ9a3B7Mfkn/3NEqKl1fNQkI9UC4=
  file: "./app/build/outputs/apk/app-debug.apk"
  on:
    repo: bosnian/curcon-android
    tag: true
